# Define the concepts for the paper
concepts_for_paper = {
                 "Chemistry": {
                "total_questions": 25,
                "concepts": {
                        "Mole Concept": 3.3,
                        "Redox Reactions": 3.3,
                        "Electrochemistry": 3.3,
                        "Chemical Kinetics": 3.3,
                        "Solution & Colligative Properties": 3.3,
                        "General Organic Chemistry": 3.3,
                        "Stereochemistry": 3.3,
                        "Hydrocarbon": 3.3,
                        "Alkyl Halides": 3.3,
                        "Carboxylic Acids & their Derivatives": 3.3,
                        "Carbohydrates, Amino-Acids, and Polymers": 3.3,
                        "Aromatic Compounds": 3.3,
                        "Atomic Structure": 6.6,
                        "Chemical Bonding": 6.6,
                        "Chemical And Ionic Equilibrium": 6.6,
                        "Solid-State And Surface Chemistry": 6.6,
                        "Nuclear & Environmental Chemistry": 6.6,
                        "Thermodynamics & the Gaseous State": 6.6,
                        "Transition Elements & Coordination Compounds": 9.9,
                        "Periodic Table": 9.9,
                }
                 },
                "Physics": {
                    "total_questions": 25,
                    "concepts": {
                        "Electrostatics": 3.3,
                        "Capacitors": 3.3,
                        "Simple Harmonic Motion": 3.3,
                        "Sound Waves": 3.3,
                        "Elasticity": 3.3,
                        "Error in Measurement": 3.3,
                        "Circular Motion": 3.3,
                        "Electromagnetic Waves": 3.3,
                        "Semiconductors": 3.3,
                        "Magnetic Effect of Current and Magnetism": 6.6,
                        "Alternating Current": 6.6,
                        "Kinetic Theory of Gases & Thermodynamics": 6.6,
                        "Kinematics": 6.6,
                        "Work, Energy, and Power": 6.6,
                        "Laws of Motion": 6.6,
                        "Centre Of Mass": 6.6,
                        "Rotational Dynamics": 6.6,
                        "Modern Physics": 6.6,
                        "Wave Optics": 6.6,
                        "Current Electricity": 9.9,
                    }
                },
                "Maths": {
                    "total_questions": 25,
                    "concepts": {
                        "Sets": 3.3,
                        "Permutations & Combinations": 3.3,
                        "Probability": 3.3,
                        "Complex Numbers": 3.3,
                        "Binomial Theorem": 3.3,
                        "Limits": 3.3,
                        "Differentiability": 3.3,
                        "Indefinite Integration": 3.3,
                        "Definite Integration": 3.3,
                        "Differential Equations": 3.3,
                        "Height & Distance": 3.3,
                        "Trigonometric Equations": 3.3,
                        "The Area under the Curve": 3.3,
                        "Quadratic Equations": 3.3,
                        "Vectors": 3.3,
                        "Tangents and Normals": 3.3,
                        "Maxima and Minima": 3.3,
                        "Statistics": 3.3,
                        "Parabola": 3.3,
                        "Ellipse": 3.3,
                        "Hyperbola": 3.3,
                        "Sequences & Series": 6.6,
                        "Straight Lines": 6.6,
                        "3-D Geometry": 6.6,
                        "Determinants": 6.6
                    }
                }
            }